package com.example.Pizzeriabackend.exception;

public enum InternalAppCode {
    BAD_ACCESS_TOKEN,
    ACCESS_TOKEN_EXPIRED,
    BAD_REFRESH_TOKEN,
    REFRESH_TOKEN_EXPIRED,
    NO_USER_PERMS,
    NO_ADMIN_PERMS,
    BAD_CREDENTIALS,
    NO_PERMISSION,
    USER_NOT_FOUND,
    RESOURCE_NOT_FOUND,
    IMPROPER_MODEL,
    INVALID_EVENT_SUBSCRIPTION,
}
