server:
  port: 8082
  address: 192.168.1.39
#  address: 192.168.127.70

image-upload-folder: ${IMAGE_UPLOAD_FOLDER:D:\Users\user\loose_projects\spring\image-upload-folder}

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:git-display}

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME:''}
    password: ${EMAIL_PASSWORD:''}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

---

spring:
  config:
    activate:
      on-profile: production

  datasource:
    driver-class-name: org.postgresql.Driver
    username: ''
    url: ''
    password: ''

  jpa:
    properties:
      hibernate:
        format_sql: true
        default_schema: ${SPRING_JPA_PROPERTIES_DEFAULT_SCHEMA:java_projekt}
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

---

spring:
  config:
    activate:
      on-profile: git-display

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:git_display_db
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true